### ISSUE TITLE
[Bug]: Firecaller doesn't aggro to iron golems and guard villagers

### ISSUE THREAD

**Issue by SireOfTheQuags** [Fuzss/illagerinvasion#25]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v.8.0.3

### Notes (Required)

The firecaller villager doesn't aggro to iron golems, guard villagers from the guard villager mod and most likely also other mobs that are naturally agressive towards illagers

**Comment by Fuzss** [comment]
From my testing targeting iron golems does work, it just takes a while to happen since the firecaller prioritizes running away from the golem if he is too close. For guard villagers, that's probably better fixed on their end. Firecallers are properly flagged as illagers for vanilla, so the mod shouldn't have any trouble recognizing them.
